name: build
on:
  pull_request:
    branches: "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: np-complete/build-book-action@3c851008c5ac01708af260fc809fcf7294a5dcf0 # v2
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: book
          path: book.pdf
